apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: host.docker.internal:5100/worker:1  # CI rewrites this tag
          envFrom:
            - configMapRef: { name: aws-config }
