apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-pipeline
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
          - env: prod
  template:
    metadata:
      name: 'aws-pipeline-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/shubhamsinghrathore/aws-job-pipeline.git  # <-- your repo
        targetRevision: main
        path: 'gitops/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pipeline-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
